### ISSUE TITLE
Config option to require all messages to be prefixed with the project name

### ISSUE THREAD

**Issue by SoniEx2** [TkTech/notifico#136]
It would be nice to have a config option to require all messages to be prefixed with the notifico project name, e.g. [User/Project] Message.

(How I wish there was a way to tag individual messages with random metadata)

**Comment by Dav1dde** [comment]
There is for github hooks, every setting is per hook not per network.

**Comment by SoniEx2** [comment]
How about add this per... notifico? As in, add it to config.py

**Comment by Croydon** [comment]
Asking here as a random pick...

@TkTech What's up with the mass closing of issues? Should we take that as a rejection of the ideas?

**Comment by TkTech** [comment]
Sorry, with so many issues some didn't get comments. This is the default for IRC in v2.0.0.

**Comment by Croydon** [comment]
Thanks for the explanation. Maybe referencing these issues in your 2.0 pull request, would make this clearer without the need for you to write into every issue 🙂
