### ISSUE TITLE
Presets for IRC channels

### ISSUE THREAD

**Issue by jlu5** [TkTech/notifico#154]
A configurable presets section in each repository's settings page would be useful, as it'd make linking multiple repositories to the same sets of channels much more convenient.

**Comment by TkTech** [comment]
In v2, the "Add New Channel" screen shows you your previously (and most recently) used channels first, before asking you to make a new one.

**Comment by TkTech** [comment]
![image](https://user-images.githubusercontent.com/72590/199463622-71fbd278-a965-4d5b-ac29-156be35a7dba.png)

Took 6 years, but you now have the option to quick-add your 3 most recent channels to the current project.
