### ISSUE TITLE
Gitea support

### ISSUE THREAD

**Issue by belliash** [TkTech/notifico#178]
Please add support for Gitea.
I have tried to setup Notifico with  my Gitea installation, but all deliveries ends up with error 500. Here are headers:

    Connection: keep-alive
    Content-Length: 3390
    Content-Type: text/html; charset=utf-8
    Date: Sun, 22 Jul 2018 12:27:13 GMT
    Server: nginx/1.10.3 (Ubuntu)
    X-Sentry-Id: 13544b2f9e824afea919610dd1ce1bfc

I can provide as many information as necessary. Just let me know.

**Comment by Croydon** [comment]
A payload example for reproduction would be helpful :)

**Comment by belliash** [comment]
Actually looks like only push event is causing error 500. Information about creating new branch is sent successfully to IRC channel.

**Comment by belliash** [comment]
Any chance to get this fixed soon?
I believe the Gitea's payload should be compatible with GitHub and even there is some difference, it should not result in internal server error...

**Comment by Dav1dde** [comment]
I initially did the github implementation and don't really have the time to look into this, from what I gather Tk is also currently very busy with other stuff, the best option for you if you want this feature soon™ is too look into it yourself.

The README shows you how to start the bots and website, then post the request to a configured webhook and check the exception you get. Either paste it here and we can help or try to fix it yourself, I'll happily review your code.

Your main entry point is here (also probably the source of the exception): https://github.com/notifico/notifico/blob/master/notifico/services/hooks/github.py

If you need any hints, I'm happy to help, you can also come by the IRC channel on freenode (#notifico).

**Comment by sdegrande** [comment]
With a working gitea + notifico setup (see issue #205), I was able to check what is wrong with the github hook. Gitea's webhooks payload is seems to be based on the Github webhooks paylod, but with a few changes (for instance, the 'compare' value is renamed 'compare_url'...)

With a simple patch, I was able to fix the 'push' notification.

Now, @TkTech, do you prefer a modified version of hooks/github.py compatible with gitea, or a whole 'new' hooks/gitea.py ?
