### ISSUE TITLE
Feature request: not to stay in the channel

### ISSUE THREAD

**Issue by minduser00** [TkTech/notifico#179]
Would be useful a couple of options, the possibility that the bot does not remain resident in the channel, but enter only at the time of sending a notification, and another to reduce the flood sending message to the channel without entering if the channel allows external messages.

**Comment by TkTech** [comment]
I don't think we're ever going to support joining, sending a message, and parting. This would definitely run afoul of automated banhammers. `NOTICE` can be used for the same effect, if the channel flags allow it.
