### ISSUE TITLE
new freenode channel added to n.tkte.ch never receives notifications

### ISSUE THREAD

**Issue by ssbarnea** [TkTech/notifico#198]
I have being using n.tkte.ch succesfuly for more than an year, with few channels and few projects but yesterday I tried to add a new channel `#ansible-galaxy` but I realised that the bot does never join the channel and does not post messages, even after 24h.

I am sure hook notifications are working because they are posted on its sister channel.

I think that the worse part about this is that there is zero information on the web interface about the channels.  My initial guess was that maybe the bot was banned, but I double checked and apparently there are no bans.

**Comment by TkTech** [comment]
Your channel is +r, meaning you've set it to only allow registered users.

**Comment by ssbarnea** [comment]
@TkTech Yeah, that is not uncommon at all on freenode as that is an effective way to avoid spam bots. All openstack channels are so, and apparently most ansible ones too. Is not really "my" channel and I doubt I can persuade them to change the policy.

Regardless if notifico supports or not registered logins, there is a perfectly valid bug that the service does not provide any insights about failures on the web interface.
