### ISSUE TITLE
too much issues already

### ISSUE THREAD

**Issue by ritche007** [TkTech/notifico#201]
Please update as you can't complete the installation anymore as it has too much errors.

**Comment by Croydon** [comment]
There is not a helpful bug report for any software maintainer. You should report what errors you have specific. Describe what you have done exactly and post a log if possible

**Comment by ritche007** [comment]
you will know what I wrote if you try to install it again on a fresh machine. Please check on your end.

**Comment by ritche007** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "notifico/__init__.py", line 12, in <module>
    from flask_caching import Cache
  File "/usr/local/lib/python2.7/dist-packages/flask_caching/__init__.py", line 412
    nonlocal source_check
                        ^
SyntaxError: invalid syntax
root@ritche:~/notifico#

Stuck on this one I sorted the other error about utopia but I managed to fix it by downloading it directly from the URL and installed. However, I am stuck now with python -m notifico init

**Comment by TkTech** [comment]
Looks like flask-caching dropped support for Py2.7 in versions after 1.7.2. You'll need to pin to it.

**Comment by ritche007** [comment]
I've redownload but still getting the same error.

**Comment by ritche007** [comment]
@TkTech I've tried after your update but still getting the same error .
