### ISSUE TITLE
libera.chat stopped working?

### ISSUE THREAD

**Issue by The-Compiler** [TkTech/notifico#202]
Thanks so much for notifico, I've now been using it without any issues for years!

Like many other projects, I've recently [moved to libera.chat](https://blog.qutebrowser.org/qutebrowser-moving-to-libera-chat.html), and also switched over [at Notifico](https://n.tkte.ch/The_Compiler/qutebrowser) (I've also tried SSL and port 6697).

This worked fine until May 27th - however, since then, I don't seem to get any notifications at all anymore. Perhaps Notifico was accidentally banned from the network or something?

**Comment by lundman** [comment]
Same problem here, libera was working, then stopped. Would rather not have to change irc networks again. :)

**Comment by ssbarnea** [comment]
I can confirm @The-Compiler report, I did extra tests and it appears that messages are not sent to libera. This may also explain why the stats page list only 20 channels on libera.

This is a serious issue as we have no clue about what happens and we are now stuck w/o notifications.

**Comment by The-Compiler** [comment]
Looks like it started working again! :tada: Closing this for now, fingers crossed it stays that way. :slightly_smiling_face:

**Comment by The-Compiler** [comment]
Apparently this broke again, at least for me, around August 20th. Can someone confirm?

**Comment by The-Compiler** [comment]
After some more investigation, it looks like it works when enabling SSL and using port 6697. When I opened this issue originally, for a while only plaintext worked. Now it seems to be the opposite, which I guess is better, but ideally both would work.

**Comment by ssbarnea** [comment]
Thanks @The-Compiler -- still the fact that this could have being fixed at database level is sad. My impression is that 95% of the users are using one of two 3 irc servers and we still all struggle to keep our notifications working doing manual work.

**Comment by The-Compiler** [comment]
Looks like it's down again now? The last time I got a notification was on October 1st, since then things have been silent.

**Comment by TkTech** [comment]
We're discussing this on IRC. There are/were too issues:

- The new automatic deployments have removed the legacy exemption for hook endpoints to be accessed over HTTP. If you have a really, really old HTTP-only webhook, just change it to https://. Sadly this is required for Github as github refuses to follow 301 redirects in webhooks. Works fine on most other services.

- SSL errors are causing the event loop in the new bots to deadlock, this is being fixed.

**Comment by TkTech** [comment]
Closing, as the bots have been running reliably for the last 24 hours.
