### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by TkTech** [TkTech/notifico#33]
Create a quick "About Notifico" page that also includes a thank you to contributors, open source dependencies and testers.

**Comment by brainwane** [comment]
If you do this, I'd also love to know how I can best thank you for creating and running the project! Signal-boosting, donating towards server hosting costs, contributing to specific upstream projects, or what have you. I'm grateful for Notifico and for http://n.tkte.ch/ and I'd love to know how best to thank you. :)
