### ISSUE TITLE
Select IRC Channels per hook

### ISSUE THREAD

**Issue by kellyelton** [TkTech/notifico#65]
It would be nice if I could have two hooks, and have each hook point to a different IRC channel within the same project. I figure maybe a list of channels when editing the hook, and the ability to switch them on and off.

**Comment by TkTech** [comment]
For the foreseeable future, I don't plan on changing the models to support this (only been 8 years!). I'm adding support for many other kinds of outputs (like slack and discord), and keeping it grouped together by project is just easiest for me.
