### ISSUE TITLE
Add support for /me (ACTION) instead of regular messages

### ISSUE THREAD

**Issue by Wolf480pl** [TkTech/notifico#86]
It would be nice if hooks had a configurable option to send messages as /me a.k.a. ACTION instead of regular messages. It would make them distinct from regular users' messages and make it easier to notice users' messages between notifico's messages.

Adding it as CTCP ACTION would be pretty easy, it would just require prepending the message with `\x01ACTION` and appending `\x01` at the end. I guess this could be done in hook.py.

Supporting the IRCv3 way of the /me command (message intents) would be more complicated, and would require whole IRCv3 feature negotiation, so I guess it's not worth implementing at the moment.

**Comment by Croydon** [comment]
Since it's totally up to the people how they configure their Notifico project I really can't see the problem.
Also worst case would be that messages look slightly different. Really not a big deal.

**Comment by TkTech** [comment]
After v2 is released, if someone wants to revive this as a PR, feel free, but I do not plan on implementing it.
